version: '3'
services:
        app:
                build:
                        context: .. # Set the context as parent dir. Set all settings from parent dir
                        args:
                                USER_UID: $USERID
                                USER_GID: $GROUPID
                        dockerfile: .devcontainer/Dockerfile
                volumes:
                        - ..:/code
                env_file:
                        - ../.env   # run ./setupEnv.sh so that above args are picked up. 
                # ports:
                #        - 9000:9000  # for the django run server
                command: sleep infinity  # donot launch anything as we will want to launch the debugger.
                depends_on:
                        - elasticsearch
                        - db

        elasticsearch:
                image: launcher.gcr.io/google/elasticsearch2
                ports:
                        - "9200:9200"
                        - "9300:9300"
                volumes:
                        - esdata:/usr/share/elasticsearch/data

        db:
                image: postgres
                restart: always
                env_file:
                        - ../.env
                environment:
                        - POSTGRES_USER=${SQL_USER}
                        - POSTGRES_PASSWORD=${SQL_PASSWORD}
                        - POSTGRES_DB=${SQL_DATABASE}
                volumes:
                        - ../data/postgres/data:/var/lib/postgresql/data
                ports:
                        - 5432:5432

volumes:
  esdata:
    driver: local

